# Accepts log level: "error", "warn", "info", "debug", "trace"
verbose = "info"
format = "detailed"
mode = "emoji"

# Base URL or website root directory to check relative URLs.
base_url = "http://localhost:1313"